package cn.ly.srms.entity;

// Generated 2017-7-13 11:33:49 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Finduserinfo generated by hbm2java
 */
public class FindUserInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private int publisher;
	private String publisherName;
	private String userName;
	private String address;
	private String school;
	private String publishTime;
	private String message;
	private String className;

	public FindUserInfo() {
	}

	public FindUserInfo(int publisher, String publisherName, String userName,
			String address, String school) {
		this.publisher = publisher;
		this.publisherName = publisherName;
		this.userName = userName;
		this.address = address;
		this.school = school;
	}

	public FindUserInfo(int publisher, String publisherName, String userName,
			String address, String school, String publishTime, String message,
			String className) {
		this.publisher = publisher;
		this.publisherName = publisherName;
		this.userName = userName;
		this.address = address;
		this.school = school;
		this.publishTime = publishTime;
		this.message = message;
		this.className = className;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getPublisher() {
		return this.publisher;
	}

	public void setPublisher(int publisher) {
		this.publisher = publisher;
	}

	public String getPublisherName() {
		return this.publisherName;
	}

	public void setPublisherName(String publisherName) {
		this.publisherName = publisherName;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getSchool() {
		return this.school;
	}

	public void setSchool(String school) {
		this.school = school;
	}

	public String getPublishTime() {
		return this.publishTime;
	}

	public void setPublishTime(String publishTime) {
		this.publishTime = publishTime;
	}

	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public String getClassName() {
		return this.className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

}
